export const USER_LOGGED_DATA = 'USER_LOGGED_DATA';
export const RESUME_DATA = 'RESUME_DATA';
export const IMAGE_DATA = 'IMAGE_DATA';
export const CONTRIBUTOR_DATA = 'CONTRIBUTOR_DATA';
export const DONATION_DATA = 'DONATION_DATA';